version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    staticcheck:
      checks:
        - all

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
